### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by Atemu** [marcusbritanicus/QtGreet#2]
I assumed this repo would have the latest state but it was silently migrated to gitlab. That fact needs to be communicated to avoid confusion.

**Comment by marcusbritanicus** [comment]
@Atemu Not migrated. github mirrors the original repo at gitlab. Perhaps I should mention somewhere though, as you suggest. :) 

Thanks.

**Comment by Atemu** [comment]
The current default branch (master) is far behind the newest on gitlab.
